import Head from "next/head";
import { Navbar } from "@/components/Navbar";
import React from "react";
import styles from "./Layout.module.scss";

interface Props {
  children: JSX.Element | JSX.Element[];
}

const Layout = ({ children }: Props) => {
  return (
    <>
      <Head>
        <title>Ecommerce</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Navbar />
        <div className={styles.container}>{children}</div>
      </main>
    </>
  );
};

export default Layout;
